name: Update OCR Data

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    name: Update OCR Data
    runs-on: ubuntu-latest

    env:
      SLACK_CHANNEL: '#general'
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Update Data File
        run: |
          pwd
          ls -la
          pip install -r requirements.txt
          python update-data.py > data.json
          if ! git diff-index --quiet HEAD --; then
            echo "OCR data file was updated."
            curl --silent --output /dev/null --show-error --request POST --header 'Content-type: application/json' --data "{'text':':money_with_wings: OCR data file was updated.','channel':'${SLACK_CHANNEL}'}" "${SLACK_WEBHOOK_URL}"
            git remote -v
            git config --local user.name "GitHub Actions"    
            git config --local user.email "actions@github.com"
            git add data.json
            git status
            # git commit -m ":money_with_wings: OCR data file updated"
          fi
          echo "done"